//
// This file generated by rdl 1.4.15. Do not modify!
//
package com.yahoo.athenz.zcs;

import com.yahoo.rdl.*;
import java.util.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

//
// ZCSHandler is the interface that the service implementation must implement
//
public interface ZCSHandler { 
    public void getSignedToken(ResourceContext context, String url, GetSignedTokenResult result);
    public void postSamlResponse(ResourceContext context, String samlResponse, PostSamlResponseResult result);
    public void getString(ResourceContext context, String url, GetStringResult result);
    public ResourceContext newResourceContext(HttpServletRequest request, HttpServletResponse response);
}
