//
// This file generated by rdl 1.4.15. Do not modify!
//
package com.yahoo.athenz.zcs;

import com.yahoo.rdl.*;
import java.util.*;
import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.inject.Inject;

@Path("/zcs/v1")
public class ZCSResources {

    @GET
    @Path("/saml/login")
    @Produces(MediaType.APPLICATION_JSON)
    public void getSignedToken(@QueryParam("url") String url) {
        try {
            ResourceContext context = this.delegate.newResourceContext(this.request, this.response);
            context.authenticate();
            GetSignedTokenResult result = new GetSignedTokenResult(context);
            this.delegate.getSignedToken(context, url, result);
        } catch (ResourceException e) {
            int code = e.getCode();
            switch (code) {
            case ResourceException.BAD_REQUEST:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.FORBIDDEN:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.TOO_MANY_REQUESTS:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.UNAUTHORIZED:
                throw typedException(code, e, ResourceError.class);
            default:
                System.err.println("*** Warning: undeclared exception (" + code + ") for resource getSignedToken");
                throw typedException(code, e, ResourceError.class);
            }
        }
    }

    @POST
    @Path("/saml/acs")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public void postSamlResponse(String samlResponse) {
        try {
            ResourceContext context = this.delegate.newResourceContext(this.request, this.response);
            PostSamlResponseResult result = new PostSamlResponseResult(context);
            this.delegate.postSamlResponse(context, samlResponse, result);
        } catch (ResourceException e) {
            int code = e.getCode();
            switch (code) {
            case ResourceException.BAD_REQUEST:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.FORBIDDEN:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.TOO_MANY_REQUESTS:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.UNAUTHORIZED:
                throw typedException(code, e, ResourceError.class);
            default:
                System.err.println("*** Warning: undeclared exception (" + code + ") for resource postSamlResponse");
                throw typedException(code, e, ResourceError.class);
            }
        }
    }

    @GET
    @Path("/saml/logout")
    @Produces(MediaType.APPLICATION_JSON)
    public void getString(@QueryParam("url") String url) {
        try {
            ResourceContext context = this.delegate.newResourceContext(this.request, this.response);
            GetStringResult result = new GetStringResult(context);
            this.delegate.getString(context, url, result);
        } catch (ResourceException e) {
            int code = e.getCode();
            switch (code) {
            case ResourceException.BAD_REQUEST:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.FORBIDDEN:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.TOO_MANY_REQUESTS:
                throw typedException(code, e, ResourceError.class);
            case ResourceException.UNAUTHORIZED:
                throw typedException(code, e, ResourceError.class);
            default:
                System.err.println("*** Warning: undeclared exception (" + code + ") for resource getString");
                throw typedException(code, e, ResourceError.class);
            }
        }
    }


    WebApplicationException typedException(int code, ResourceException e, Class<?> eClass) {
        Object data = e.getData();
        Object entity = eClass.isInstance(data) ? data : null;
        if (entity != null) {
            return new WebApplicationException(Response.status(code).entity(entity).build());
        } else {
            return new WebApplicationException(code);
        }
    }

    @Inject private ZCSHandler delegate;
    @Context private HttpServletRequest request;
    @Context private HttpServletResponse response;
    
}
